### ISSUE TITLE
Captions for memes are cut off

### ISSUE THREAD

**Issue by adrian-fjellberg** [Nudes-Token/feedback#1]
**Whats the issue?**
When the caption on memes are too long they get cut of.

![image](https://user-images.githubusercontent.com/7628745/173597075-f34ac535-509c-41e0-8349-684dd3aaae12.png)

**Possible solution**
Maybe we can use a smaller font or let the caption break to a new line?

Original report:
https://discord.com/channels/928449627383037953/974677207400185856/986257024385974324

**Comment by Geralt-of-R1via** [comment]
1. We can break long tittles into new rows but that's gonna expand across the whole page. In a few months when there is 100-200 memes daily and half of them break title into a few rows, that's gonna be killer for mobile users.
2. Restrict the number of letters available for the tittle

**Comment by adrian-fjellberg** [comment]
> 1. We can break long tittles into new rows but that's gonna expand across the whole page. In a few months when there is 100-200 memes daily and half of them break title into a few rows, that's gonna be killer for mobile users.
> 2. Two rows max with smaller font or...
> 3. Restrict the number of letters available for the title with current size font

Thanks for input @Geralt-of-R1via. I think restricting the number of characters to 30 max and then having a smaller font size is the way to go.

@Topstar-web Can you add a validation for the title length should not be more than 30 characters on when creating a meme? Also, when displaying a meme, if the character count is less than 20 characters you can use a bigger font.

@NeoDashboard Can you add a validation for 30 characters max for meme title on backend?

**Comment by odd86** [comment]
Fixed
