### ISSUE TITLE
Posting a meme gives up an "Error" pop up, but posts successfully.

### ISSUE THREAD

**Issue by zatouroff** [Nudes-Token/feedback#11]
When I Mint&Publish a meme, next pop-up screen shows an error as shown in the screenshot below. But it was successful since I can see my memes on the website. Posted 3 memes, 2 of them gave an error screen. All of them are published.

https://i.ibb.co/hCTpjG0/error-after-clicking-mint-and-publish.jpg

 - OS X 12.2.1
 - Firefox
 - v 101.0.1

**Comment by BorisOG** [comment]
I will just add that this is also what I experienced and after error it is successful posted but counter is not working, it is not updating that new meme is posted 1/3 and I posted 2.

**Comment by adrian-fjellberg** [comment]
> When I Mint&Publish a meme, next pop-up screen shows an error as shown in the screenshot below. But it was successful since I can see my memes on the website. Posted 3 memes, 2 of them gave an error screen. All of them are published.

Could you open console in the browser next time to see if there is any errors? Also check the "Network" tab in the developer console in the browser. Do you know how to do this?

**Comment by BorisOG** [comment]
@adrian-fjellberg 
https://development.nudes-army-webpage.pages.dev/view/6f7c9f7e-55de-4766-910f-58928d4091fc
https://development.nudes-army-webpage.pages.dev/view/e8136bb7-e16d-4fce-81ea-95f1a4c5f47c
![not updating](https://user-images.githubusercontent.com/107487995/173684950-a98c94ab-a4bf-4d5a-81bb-0b8450c08670.JPG)

**Comment by zatouroff** [comment]
> > When I Mint&Publish a meme, next pop-up screen shows an error as shown in the screenshot below. But it was successful since I can see my memes on the website. Posted 3 memes, 2 of them gave an error screen. All of them are published.
> 
> Could you open console in the browser next time to see if there is any errors? Also check the "Network" tab in the developer console in the browser. Do you know how to do this?

Yeah, I'll notify when it happens again.

**Comment by odd86** [comment]
I have not seen this, so if it happens again please get as much info as possible and re-open :)
