### ISSUE TITLE
Tooltip on "My account" not working

### ISSUE THREAD

**Issue by BorisOG** [Nudes-Token/feedback#13]
![if you don't have nft this needs to tell you](https://user-images.githubusercontent.com/107487995/173685863-b48bae21-2e9e-4f7a-a3c8-b07edb2841ca.JPG)

As you see when you click, it will not show anything, it is empty ( no options ) 

--- Edit by atlazor ---

Adding context/feedback from user:
> My account segment on the right side where you can see discount if you own NFT and [ ? ]  in circle is not doing anything it needs to show information and guide how to get % discounts.

**Comment by adrian-fjellberg** [comment]
@Topstar-web Is this the tooltip issue?

**Comment by zatouroff** [comment]
Rusty said it was working in Chrome, but it's not showing anything in Firefox (v 101.0.1 / OS X) too.

**Comment by odd86** [comment]
Should work in next build.
