### ISSUE TITLE
Comment feature not working on single meme page

### ISSUE THREAD

**Issue by Geralt-of-R1via** [Nudes-Token/feedback#16]
When you click on the meme image and a new tab appears. Comment feature is not working on that new page

https://discord.com/channels/928449627383037953/974677207400185856/986395375017545788

**Comment by adrian-fjellberg** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/7628745/175012058-a77e90d0-b5af-4039-9baa-4b0a32af613f.png">

**Comment by adrian-fjellberg** [comment]
@Geralt-of-R1via I am not able to replicate the "comment button dosn't work" action. Are you?
