### ISSUE TITLE
Comment button not working on page after clicking on a meme

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#18]
After clicking a meme I am taken to a page with just that meme, but the comment button does not work on that page. 

<img width="665" alt="Screen Shot 2022-06-14 at 8 46 46 PM" src="https://user-images.githubusercontent.com/107487385/173712920-bd8a4755-3ef4-4224-a475-29a6efbd4c57.png">

**Comment by adrian-fjellberg** [comment]
Hello @hellobordois. I created a separate issue for comments and I think this should fix the issue at the same time https://github.com/Nudes-Token/feedback/issues/22

@Topstar-web, if it's an easy fix to the issue Bordois stated above, then please fix it before we implement the new comment logic/design.

**Comment by odd86** [comment]
Fixed
