### ISSUE TITLE
Top Creators Username and NUDES number are awfully close to each other and will cross over eventually

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#19]
Top Creators Username and NUDES number are awfully close and will cross over eventually.

<img width="311" alt="Screen Shot 2022-06-14 at 8 49 58 PM" src="https://user-images.githubusercontent.com/107487385/173713301-899d7247-f7e2-44b1-8146-bc0029e1c9ef.png">

**Comment by adrian-fjellberg** [comment]
Maybe change to number with unit suffix? In the case in your screenshot it would display `17.78M` istead of `17,785,360`.

@Topstar-web Can you change to use `:unit-suffix="true"` and use `<flm-number />` here if not already done?

**Comment by odd86** [comment]
Fixed
