### ISSUE TITLE
Date/time stamp incorrect on comment

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#21]
Date/time stamp incorrect on comment

<img width="471" alt="Screen Shot 2022-06-14 at 9 38 10 PM" src="https://user-images.githubusercontent.com/107487385/173717901-6719ea73-d4dd-4b62-8e33-f204079a9dbb.png">

**Comment by adrian-fjellberg** [comment]
@Topstar-web Maybe the timestamp needs to be divided by `1,000`? Can you see if you can resolve this issue?

**Comment by hellobordois** [comment]
Interesting, the screenshot I originally posted in the issue was this comment, and the date and time stamp are fixed now. 

<img width="467" alt="Screen Shot 2022-06-15 at 2 38 51 PM" src="https://user-images.githubusercontent.com/107487385/173900841-e6092b3e-a952-43ea-94f2-c990bfd51f8d.png">

**Comment by odd86** [comment]
Ok, re-open if it apairs again ;)

**Comment by adrian-fjellberg** [comment]
I found that the timestamp was incorrect if I made a new comment (and did not refresh the page). My newly added comment had the wrong date @odd86 @hellobordois

**Comment by hellobordois** [comment]
Reopened: Still getting incorrect date/time stamp when commenting.

<img width="471" alt="Screen Shot 2022-06-15 at 4 13 37 PM" src="https://user-images.githubusercontent.com/107487385/173918710-4afd5ddf-036a-40d7-bdb6-7f970772583f.png">

**Comment by hellobordois** [comment]
@odd86 So even though it still happens on new comments we should let that happen?

**Comment by adrian-fjellberg** [comment]
> @odd86 So even though it still happens on new comments we should let that happen?

I think he means that he fixed the issue with wrong timestamp on the new comments 😄

**Comment by odd86** [comment]
The issue is fixed and is being deployed

**Comment by hellobordois** [comment]
Ah, it wasn't deployed yet. Sorry :)
