### ISSUE TITLE
Highlighted topic is not in sync in both sections

### ISSUE THREAD

**Issue by zatouroff** [Nudes-Token/feedback#23]
<img width="1072" alt="Screen Shot 2022-06-15 at 13 57 32" src="https://user-images.githubusercontent.com/107487661/173811388-35983bf9-dda1-4393-9081-0c403027647b.png">

When HOT topic is selected from top bar, it's also highlighted on left bar. If I click Trending/Fresh at top bar, left bar stays highlighted on HOT.

But, if I click Trending or Fresh on left bar, both top and left bar highlights the right topic until I click HOT again. Then it's highlight gets stuck again.

**Comment by odd86** [comment]
Fixed

**Comment by odd86** [comment]
Hmm, still a bug if you click a lot on different filters

**Comment by odd86** [comment]
Fixed by @adrian-fjellberg

**Comment by zatouroff** [comment]
@adrian-fjellberg I've started experiencing the same problem again.
