### ISSUE TITLE
After comment it opens voting for last bottom comment

### ISSUE THREAD

**Issue by odd86** [Nudes-Token/feedback#24]
**Describe the bug**
When I post a comment, the bottom comment voting gets opened

**To Reproduce**
1. Go to a meme
2. Click on comment emoji
3. Make a comment
4. See that the voting opens

**Expected behavior**
That voting does not open

![image](https://user-images.githubusercontent.com/7629853/173819473-645d977d-6759-4e73-9143-9b9aba6a494f.png)

**Comment by adrian-fjellberg** [comment]
@Topstar-web Can you fix this please?

**Comment by odd86** [comment]
Fixed

**Comment by adrian-fjellberg** [comment]
@odd86 I am still getting this bug. Sure it is fixed?

**Comment by zatouroff** [comment]
> @odd86 I am still getting this bug. Sure it is fixed?

Still when I click "upvote meme" button while the comment section is open, NUDES quantity input panel teleports to the bottom of the page, below the comments.

<img width="691" alt="Screen Shot 2022-06-16 at 14 38 42" src="https://user-images.githubusercontent.com/107487661/174062269-8cf5c8cd-e226-4fab-807f-39d5ffb23d16.png">

**Comment by adrian-fjellberg** [comment]
> Still when I click "upvote meme" button while the comment section is open, NUDES quantity input panel teleports to the bottom of the page, below the comments.

Seems like a different bug. I will create a separate issue for this.
