### ISSUE TITLE
Typos/copy errors in sign up modal

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#27]
There are a few typos/copy changes to be made to the Sign Up form.

**Create your NUDES Army account** should be **Create your Nudes Army account** 

**start earning NUDES!.** should be **start earning NUDES!**

**Sing up with Twitter** button should be **Sign up with Twitter**

![image](https://user-images.githubusercontent.com/107487385/173833514-f5da5521-eb5f-46d6-8ca3-c7b0f36eba76.png)

**Comment by odd86** [comment]
Fixed
