### ISSUE TITLE
Posted comment doesn't show until the page is refreshed

### ISSUE THREAD

**Issue by zatouroff** [Nudes-Token/feedback#28]
https://discord.com/channels/928449627383037953/976552960395984946/986626928003911687

war3rd — I made a comment but I would recommend having the comment count "refresh" when a comment is added. There were 2 comments on a meme, I made another, but it still shows 2 comments unless I refresh the page. (he's using Chrome)

zatouroff — It's working fine on my side, I can see my own posted comment without refreshing anything. Firefox 101.0.1 OS X

**Comment by adrian-fjellberg** [comment]
Found out how to replicate the bug:

1. Make a comment
2. Close the comment modal
3. Look at the comment count on the meme (not the count in the modal)
4. It has not been updated with the new count (a refresh is needed to see correct count)

Tagging you so you see it @odd86 (if you are working on comments right now)

**Comment by odd86** [comment]
Fixed
