### ISSUE TITLE
Show more "Top Creators" in sidebar

### ISSUE THREAD

**Issue by adrian-fjellberg** [Nudes-Token/feedback#29]
**Is your feature request related to a problem? Please describe.**
I want to see more of the "Top Creators" in the sidebar! 😡 5 IS NOT ENOUGH 😆 

**Describe the solution you'd like**
It would be nice to see at least 10 "Top Creators" or implement the same "Show more" functionality as in the category section above.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/7628745/173908756-e944bddd-dd2e-4410-8d63-2be28fbd61ce.png">

**Comment by odd86** [comment]
It is made a new design for Top Creators, Top Voters, Top Commenters.
It will also be a separate page that you can see top 100 if you want to see more :)

**Comment by adrian-fjellberg** [comment]
We could also add a number indicating the placement?

<img width="257" alt="image" src="https://user-images.githubusercontent.com/7628745/173909335-6bf61bda-c8cd-48d1-82e7-2d01b9449491.png">

**Comment by odd86** [comment]
Added a button "See More" To go to rankings where you can find a lot of sexy stats
![image](https://user-images.githubusercontent.com/7629853/174151191-00d38a97-4892-4420-9ed8-6654b04ca1c3.png)
