### ISSUE TITLE
Error message when you have Insufficient NUDES balance when making a comment.

### ISSUE THREAD

**Issue by adrian-fjellberg** [Nudes-Token/feedback#31]
**Describe the bug**
When you have insufficient balance to make a comment, the error message in the toast shown is empty.

**To Reproduce**
1. Have a less than 69,420 NUDES in your balance.
2. Try to comment on a meme.
3. See that the error toast on top of the page is empty.

**Expected behavior**
I expect a more concise description of the error. Message can be `Insufficient NUDES balance`.

**Screenshots**

<img width="532" alt="image" src="https://user-images.githubusercontent.com/7628745/173914829-8f1e2e13-1475-45f0-9788-1eebfeaf8de4.png">

**Comment by odd86** [comment]
Fixed
