### ISSUE TITLE
Burn counter

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#32]
We had added to the article that there would be a fireplace burn counter on the site and I know @FreezzCrypto designed it but I do not see it. 

When someone upvotes a meme or a comment, the NUDES burn queue counter on discord should go up as well as a fireplace burn counter on the memes page.

**Fireplace Burn Counter**
A Fireplace Burn Counter shows the number of NUDES to be burned, and later will link to an interactive Nudes Army Fireplace page.

**Comment by adrian-fjellberg** [comment]
It was removed from the site as the UX for it was really confusing for that "sidebar widget". I think it is better to add it back in once the Fireplace page has been implemented. Please remove that paragraph from the article @hellobordois.

**Comment by hellobordois** [comment]
@adrian-fjellberg I also just tested to make sure the upvotes are changing the Burn Queue Counter on Discord but they aren't. Might have to bring NeoDashboard in on this one. Shall we open this issue back up?

**Comment by adrian-fjellberg** [comment]
> Might have to bring NeoDashboard in on this one. Shall we open this issue back up?

Could you open a new one, as this issue relates to the burn counter on the site?

I will change the title on this issue to make it clearer for later reference.
