### ISSUE TITLE
Commenting cost tooltip copy edits

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#37]
Change **up votes** to **upvotes** in first sentence.

Change **Your diversifier** to **Your Fee Discount** and change to percentage.

<img width="236" alt="Screen Shot 2022-06-16 at 1 27 22 PM" src="https://user-images.githubusercontent.com/107487385/174130953-1268cf63-8b92-4ee4-887b-8afab6eb79c7.png">

**Comment by odd86** [comment]
Fixed in next build
