### ISSUE TITLE
Clicking on a notification doesn't open it's page while you are in a single meme page (not on landing page).

### ISSUE THREAD

**Issue by zatouroff** [Nudes-Token/feedback#38]
**Describe the bug**
While you are checking out a single meme page, clicking a notification doesn't take you to that page. But it works while you are on the landing page (nudes.army)

**To Reproduce**
1. Go to a single meme page.
2. Click on notification panel.
3. Click "X upvoted your comment" / "X commented on your meme".
4. Error: Page doesn't change.

**Expected behavior**
Page should change to the meme I got upvoted / commented.

**Screenshots**

**Desktop (please complete the following information):**
 - Mac 12.2
 - Firefox
 - 101.0.1

**Comment by odd86** [comment]
Sweet, I will fix this

**Comment by odd86** [comment]
Fixed
