### ISSUE TITLE
Meme shows comments from a different meme

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#40]
**Describe the bug**
Meme shows comments from a different meme

**To Reproduce**
1. look at comments on one meme
2. Get notified about a different meme
3. Click on that notification
4. See the new meme but the comments are from the other meme you were looking at

**Expected behavior**
When I see the meme from the notifications link I expect to see the comments associated with that meme. 

<img width="723" alt="Screen Shot 2022-06-17 at 8 51 59 AM" src="https://user-images.githubusercontent.com/107487385/174302336-6c778e49-88fb-4a3f-9d25-ecc869bc8a41.png">

**Comment by odd86** [comment]
Yes :)
