### ISSUE TITLE
Meme-to-earn channels on Discord not working

### ISSUE THREAD

**Issue by adrian-fjellberg** [Nudes-Token/feedback#46]
**Describe the bug**
The Meme-to-earn channels on Discord not working.

**To Reproduce**
1. Post, upvote or downvote a meme
2. Go to discord and check channels under "MEME TO EARN"
3. No updates...

**Expected behavior**
We want the posts, upvotes or downvotes to be reflected on Discord to drive even more engagement. The people with a lot of NUDES on Discord will vote and encourage new users to create more memes.

**Comment by odd86** [comment]
I would say this is not a bug as I have not find a conclusion on how we want it and what is best for the site

**Comment by adrian-fjellberg** [comment]
> I don't know if we want images in the channel? maybe just links?
> We want the users to get on the site and vote and scroll

Yeah I think links only are a good idea. My thought is that we can use Discord to encourage people to vote on fresh memes, as not everyone will browse the fresh categories.
