### ISSUE TITLE
Clicking a notification changes the meme but not the comments

### ISSUE THREAD

**Issue by zatouroff** [Nudes-Token/feedback#52]
**Describe the bug**
Clicking a notification changes the meme but not the comments

**To Reproduce**
1. Open a single meme page and expand the comment section.
2. Click on your username on right bar and click a notification to change the meme.
3. See error. Meme changes but comments not.
4. Click another notification, meme changes again but comments not.
5. Rinse and repeat.

**Expected behavior**
Both image and comments has to change in sync.

**Screenshots**
Both screenshot comments are from my LETT UCE meme. Clicked my notifications, and comments didn't sync.

![Screenshot 2022-06-19 at 23-29-58 $NUDES MEME-TO-EARN!](https://user-images.githubusercontent.com/107487661/174499410-10c90400-7b06-4a51-aabf-7272ac3fbc9f.png)

![Screenshot 2022-06-19 at 23-29-24 $NUDES MEME-TO-EARN!](https://user-images.githubusercontent.com/107487661/174499412-3b329ca0-ff9c-44e4-b129-9f0b0b32e243.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - 101.0.1

**Comment by zatouroff** [comment]
2 hours passed, it didn't happen after I've visited the website again on a new tab. Glad I took the screenshots tho. Not closing this issue in case you might miss it.

**Comment by adrian-fjellberg** [comment]
@zatouroff I am able to confirm that this bug sill persists.

@Topstar-web Can you see if you can fix this?

**Comment by Topstar-web** [comment]
https://github.com/Nudes-Token/nudes-army-webpage/pull/26
fixed.
