### ISSUE TITLE
User complains 2 Hired Gun NFTs is only getting him 11% off fees but should get him 15% off fees

### ISSUE THREAD

**Issue by hellobordois** [Nudes-Token/feedback#55]
User complains holding 2 Hired Gun NFTs is only getting him 11% off fees but he thinks it should get him 15% off fees.

OG NFTs give 50% off for one, and 75% off for two. Shouldn't Hired Gun NFTs give 10% off for one, and 15% off for two?

**Comment by adrian-fjellberg** [comment]
@hellobordois Can you contact the user and make him check if it is correct now? I think this has been fixed.
