### ISSUE TITLE
Information on the V2 site is outdated

### ISSUE THREAD

**Issue by adrian-fjellberg** [Nudes-Token/feedback#6]
**Describe the bug**
The information on the V2 site is outdated. The following pages should be updated:

- "Project & Ecosystem": https://development.nudes-army-webpage.pages.dev/what-is-nudes-token
- "Get started": https://development.nudes-army-webpage.pages.dev/get-started

**Expected behavior**
I expect the information to be up to date with the new features and how the site works.

@hellobordois has written an article that can be used as the basis for the "Project & Ecosystem"-page.

Could you maybe make some changes to the copy @hellobordois so that it fits in the content of a web page?

--------- ARTICLE FROM BORDOIS ---------

Nudes Army Launches Major Meme-To-Earn Site Updates

Fellow Nudists of the World! 

It's finally here… the moment you have all be waiting for… (actually it has only been seven weeks since the launch of Version 1 but STILL!) Version 2 (V2) of the Nudes Army Meme-to-Earn site is here! 

What's New in Version 2?

A New Way to Earn and Recruit
Out with the old and in with the NUDES. Before V2 of the Nudes Army MemeSite, you could send NUDES to get NUDES, and if you were a brand new user, you could use the NUDES Faucet to get some NUDES, too. Going forward we have chosen to discontinue those ventures. While they were an excellent way to earn and recruit, we think V2 of the MemeSite will bring even better ways to earn MORE NUDES and recruit MORE NUDES ARMY. Keep reading to find out how. 

Commenting
In V2 you can comment. Commenting will require a fixed fee that goes towards upvotes on the meme, so if you try to be foolish with your comments, you at least need to pay for it. Comments can also get NUDES upvotes and downvotes and will have the same mechanics as voting on a meme.

Multi-Token Support
V2 of the MemeSite was built to be able to support other tokens easily in the future.

Twitter Login
Users can now log into the MemeSite with their Twitter account. This feature uses "hot wallets" for super quick onboarding of new users. New users won't need a Neo N3 wallet before they can start creating memes. 

Unclaimed Rewards
A new Unclaimed Rewards section gathers all rewards from your platform usage and tasks.

Fireplace Burn Counter
A Fireplace Burn Counter shows the number of NUDES to be burned, and later will link to an interactive Nudes Army Fireplace page.

Top Creators
A new Top Creators section will show the top five creators with the most upvotes at any given time.

Consume-To-Earn - Daily Bonus
There will now be a Daily Bonus where users can "consume to earn" by completing a daily set of tasks to earn more NUDES.

Also every day you will get 17 NUDES per SECOND for just having an account!

And it's all "free" NUDES for you! The advertisers pay you for consuming, you pay the meme creators by upvoting their memes, and the creators make content that you enjoy.

Marketing Incentives
Do you have a lot of followers? Nice! Share referral codes and we'll give you NUDES rewards based on how many users come to the site via your referral link. As a marketer you can make money by promoting nudes.army. Everyone will earn NUDES from sharing, and "big players" can earn even more.

Improved User Interface
An improved Create Meme interface makes it easier to upload memes. 

Hot Wallet Deposit and Withdrawal
Users can now deposit and withdraw NUDES from a hot wallet (linked to Twitter) to their personal Neo N3 wallet.

NFT Multipliers
There is also NFT multipliers on everything. If you have a Nudes Army OG NFT, for example, you will get more NUDES as upvotes and more NUDES for engaging with the site. You will also get fee discounts. And NFT benefits are stackable. See the Rewards and Fees section below.
Project and Company Marketing and Advertisement (Coming Soon)
The site will also soon include advertisement spots for companies and projects. Any projects who wish to advertise must pay in NUDES which will add buying pressure to NUDES.
Companies and projects who do want an ad spot must mint an NFT and pay the price; the NUDES spent on this NFT will be distributed as follows:
- 50% will go to consumers
- 30% will be burned
- 20% will go to the single-stake fund

Projects and companies can also hire the Nudes Army to make memes for their project. To get a winner they need to send their users/community to sign up on our page (with Twitter) and use a promo code. The project then needs to buy NUDES from the market and when the contest starts, NUDES is airdropped to all that are registered with the promo code so they can vote. This will all happen with hot wallets.
Rewards and Fees
"Minting" refers to NUDES tokens taken from the total supply. No new NUDES tokens will ever be minted into creation. The total supply of NUDES will always be deflationary. 
Rewards for having an account

1,500,000 NUDES per day (17.36 per second)

Rewards for making an account
When you make an account you get 1,000,000 NUDES to use on the platform (you can't just withdraw them)

If you use a referral code on signup you get 500,000 MORE NUDES

Daily bonuses (need to be completed within 24h) 
- Consuming memes (100 loads): 500,000 NUDES 
- Posting memes (3 memes): 1,500,000 NUDES 
- Voting on memes (10 memes): 1,000,000 NUDES 
- Comment on memes (10 memes): 500,000 NUDES 
- Vote on comment (10 memes): 250,000 NUDES 
- Invite Bonus (10 referrals): 1,500,000 NUDES 
- Share link clicks (100 clicks): 500,000 NUDES 

Recurring bonus 
Invites (unlimited): 500,000 NUDES per successful referral (the user must create an account on nudes.army)

Fees (NFT discount is deducted)
- Post a Meme: 1,000,000 NUDES 
- Vote on a Meme: 0 NUDES 
- Comment on a Meme: 69,420 NUDES (counts as upvotes for the meme) 
- Vote on a Comment: 0 NUDES 
- Withdrawal fee: 1% (minus NFT fee discount - see below)+ 30,000,000 NUDES

Withdrawal Threshold
A  withdrawal threshold is the amount of NUDES tokens you can withdraw from the platform. You build up your withdrawal threshold by using the platform. Every daily task gives you 5% of the amount to withdraw, plus any NFT discount/reward you may have (e.g. if you have an OF NFT, you will get 7.5% to withdraw).

To get a higher withdrawal threshold you need to use the platform. All things you do on the platform (voting, creating memes, commenting, and so on) gives you the same amount of NUDES you used in the increased withdrawal threshold. 

NUDES deposits give you a 100% withdrawal threshold of the deposited NUDES. 

Nudes Army NFTs
- Holding a Nudes Army OG NFT gives you a 50% reward multiplier and 50% fee discount. 
- Holding a Nudes Army Hired Gun NFT gives you a 10% reward multiplier and 10% fee discount. 
- NFTs are stackable so if you hold 2 OG NFTs you'll get a 75% reward multiplier and 75% fee discount.

* Rewards and Fees are subject to change based on the price of NUDES and overall site usage.

So, whether you are a consumer, creator, influencer, company, project, investor, or all of the above, the Nudes Army MemeSite has something for you, and we hope you come enjoy it with us.

**Comment by adrian-fjellberg** [comment]
Here is the copy that @hellobordois wrote for the "Get started" page.

```
Get Started with NUDES!

Step 1: In order to participate in the Nudes Army platform, you'll first need a Twitter account. If you don't have one, you can make one here.

Step 2: On the Nudes Army platform, select Log in with Twitter in the upper righthand corner. If you have one, enter your referral code. Select Log in with Twitter once more, then authorize the app. 

That's it! You can now start posting, voting on, and commenting on awesome memes, and earning daily rewards! 
```

**Comment by adrian-fjellberg** [comment]
Maybe the pages should have a new design?

I will ask Freezz if he can make something once @hellobordois is done with finalizing the copy for the "Project & Ecosystem page.

But even before we have a new design I think Shinestar can implement the new copy/text ASAP. Could you please do that @Topstar-web ?

**Comment by hellobordois** [comment]
Yes I will write new copy for the Project and Ecosystem page.

**Comment by adrian-fjellberg** [comment]
@FreezzCrypto Could you make a design with the copy above for the following pages?

1. "Get started"-page
2. "Project & Ecosystem"-page

Make it as sexy as you want with supplementary graphics, but remember to add mobile view to the design (so maybe not to complicated 😅 )

**Comment by adrian-fjellberg** [comment]
Tagging you here @odd86, if you are not already subscribed to this issue.

@FreezzCrypto has made design for the static pages that are more welcoming and pleasing to the eye for new users. When we implement this design and remove the big hero on the frontpage I think we are much better off 😄 

The design can be found here:
https://www.figma.com/file/zknavu2MaNQx4wlRTRGybb/Meme-to-Earn-V2?node-id=957%3A304

**Comment by adrian-fjellberg** [comment]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/7628745/174064448-c1c32c15-5453-4ea5-92ec-1b88f515b493.png">

**Comment by odd86** [comment]
Fixed by @adrian-fjellberg

**Comment by hellobordois** [comment]
@odd86 can you delete the period after Twitter, the sentence ends after righthand corner. 

<img width="284" alt="Screen Shot 2022-06-17 at 6 45 33 AM" src="https://user-images.githubusercontent.com/107487385/174283781-beeede5b-6fff-4f97-b16e-647a2d6ab56b.png">

**Comment by adrian-fjellberg** [comment]
> can you delete the period after Twitter, the sentence ends after righthand corner.

Should be fixed in next push. In a bout 5 minutes from now.

**Comment by hellobordois** [comment]
@adrian-fjellberg @odd86 the links are backwards I think :D get started goes to project and what is nudes goes to get started.

**Comment by hellobordois** [comment]
(on the banner)
