### ISSUE TITLE
Wrong hover text for voting posts

### ISSUE THREAD

**Issue by zatouroff** [Nudes-Token/feedback#67]
To replicate the bug;

Open a random post in new tab: https://nudes.army/view/bf1a2643-7126-45f9-823f-0da6501e83d2

Wanted to vote the post but voting button says "comment":
![Screenshot 2022-08-28 220536](https://user-images.githubusercontent.com/107487661/187091034-ad8b232f-5b25-4da7-bbcc-76aa9da5e9cc.png)

Then Vote or click cancel: (This thing opens at bottom, made me confused a little bit. Thought it vanished)
![Screenshot 2022-08-28 220608](https://user-images.githubusercontent.com/107487661/187091061-a16ba92f-d981-4403-bb21-cb83b0f2a5d2.png)

Voting button now says "post":
![Screenshot 2022-08-28 222240](https://user-images.githubusercontent.com/107487661/187091074-3cb8e157-20c7-4cda-a6bb-f3eadaf86e89.png)

**Comment by adrian-fjellberg** [comment]
Fixed. Should be live in 5 minutes.
