### ISSUE TITLE
+ show more button is showing only few categories before click + when you click there is no show less button to go back

### ISSUE THREAD

**Issue by BorisOG** [Nudes-Token/feedback#8]
+ show more button is showing only few categories before click + when  you click there is no show less button to go back.
![picture 1](https://user-images.githubusercontent.com/107487995/173665129-aa797056-c569-43d8-a423-5f24482c073a.JPG)
![picture 2](https://user-images.githubusercontent.com/107487995/173665132-fd19d0f2-a67c-45e8-b01a-b5cfbae8b352.JPG)

**Comment by adrian-fjellberg** [comment]
@Topstar-web Could you add a "Sow less" button? 🙏  Can be the same style as "Show more".

**Comment by odd86** [comment]
Fixed
